
// Update script for vtuberModels.js
// Copy these thumbnail paths to your model entries

const thumbnailPaths = {
    "APHO2 Bronya": "vtuber/thumbnails/apho2_bronya.jpg",
    "Acacia Kaguya": "vtuber/thumbnails/acacia_kaguya.jpg",
    "Ai Hoshino": "vtuber/thumbnails/ai_hoshino.jpg",
    "Alyss": "vtuber/thumbnails/alyss.jpg",
    "Anya Forger": "vtuber/thumbnails/anya_forger.jpg",
    "Avatar 3D Aria": "vtuber/thumbnails/avatar_3d_aria.jpg",
    "Azur Lane Enterprise": "vtuber/thumbnails/azur_lane_enterprise.jpg",
    "Beatrice": "vtuber/thumbnails/beatrice.jpg",
    "Bronya HoTr": "vtuber/thumbnails/bronya_hotr.jpg",
    "Carlotta": "vtuber/thumbnails/carlotta.jpg",
    "Caroline": "vtuber/thumbnails/caroline.jpg",
    "Cesilia": "vtuber/thumbnails/cesilia.jpg",
    "Changli": "vtuber/thumbnails/changli.jpg",
    "Chen Qianyu": "vtuber/thumbnails/chen_qianyu.jpg",
    "Cipher": "vtuber/thumbnails/cipher.jpg",
    "Clorinde": "vtuber/thumbnails/clorinde.jpg",
    "DUST": "vtuber/thumbnails/dust.jpg",
    "DreamSeeker": "vtuber/thumbnails/dreamseeker.jpg",
    "Dushevnaya": "vtuber/thumbnails/dushevnaya.jpg",
    "Eula Lawrence": "vtuber/thumbnails/eula_lawrence.jpg",
    "Fern VT model": "vtuber/thumbnails/fern.jpg",
    "Freestyletest": "vtuber/thumbnails/freestyletest.jpg",
    "Galih Hoodie": "vtuber/thumbnails/galih_hoodie.jpg",
    "Galih Hoodie Edmuku": "vtuber/thumbnails/galih_hoodie_edmuku.jpg",
    "Galih Hoodie Esteh": "vtuber/thumbnails/galih_hoodie_esteh.jpg",
    "Galih T shirt Aveecena": "vtuber/thumbnails/galih_tshirt_aveecena.jpg",
    "Goldy": "vtuber/thumbnails/goldy.jpg",
    "Guinaifen": "vtuber/thumbnails/guinaifen.jpg",
    "Haruhi Suzumiya Long hair": "vtuber/thumbnails/haruhi_suzumiya.jpg",
    "Herrscher of Finality": "vtuber/thumbnails/herrscher_of_finality.jpg",
    "iCO Gore": "vtuber/thumbnails/ico_gore.jpg",
    "Jingliu HSR": "vtuber/thumbnails/jingliu_hsr.jpg",
    "Kiana Kaslana": "vtuber/thumbnails/kiana_kaslana.jpg",
    "Kirito": "vtuber/thumbnails/kirito.jpg",
    "Kokuyou": "vtuber/thumbnails/kokuyou.jpg",
    "Lilac": "vtuber/thumbnails/lilac.jpg",
    "Luna": "vtuber/thumbnails/luna.jpg",
    "Lunar New Year's Eve": "vtuber/thumbnails/lunar_new_years_eve.jpg",
    "Magical girl sirin": "vtuber/thumbnails/magical_girl_sirin.jpg",
    "Maya2": "vtuber/thumbnails/maya.jpg",
    "Meryl": "vtuber/thumbnails/meryl.jpg",
    "Ming Chao": "vtuber/thumbnails/ming_chao.jpg",
    "Mizuhara Chizuru": "vtuber/thumbnails/mizuhara_chizuru.jpg",
    "MMORPG Mage": "vtuber/thumbnails/mmorpg_mage.jpg",
    "Mura Mura": "vtuber/thumbnails/mura_mura.jpg",
    "Navia": "vtuber/thumbnails/navia.jpg",
    "Neku Shiro": "vtuber/thumbnails/neku_shiro.jpg",
    "Nemesis C3": "vtuber/thumbnails/nemesis_c3.jpg",
    "Neuro-Sama": "vtuber/thumbnails/neuro_sama.jpg",
    "Nezuko Kamado": "vtuber/thumbnails/nezuko_kamado.jpg",
    "Nico Robin": "vtuber/thumbnails/nico_robin.jpg",
    "Niya": "vtuber/thumbnails/niya.jpg",
    "Oni": "vtuber/thumbnails/oni.jpg",
    "Prinz Eugen": "vtuber/thumbnails/prinz_eugen.jpg",
    "QiongJiu": "vtuber/thumbnails/qiongjiu.jpg",
    "Raiden Mei": "vtuber/thumbnails/raiden_mei.jpg",
    "Ram": "vtuber/thumbnails/ram.jpg",
    "Rem": "vtuber/thumbnails/rem.jpg",
    "Renni": "vtuber/thumbnails/renni.jpg",
    "Rose": "vtuber/thumbnails/rose.jpg",
    "RX-0 Unicorn": "vtuber/thumbnails/rx0_unicorn.jpg",
    "Serina Washimi": "vtuber/thumbnails/serina_washimi.jpg",
    "Shirli": "vtuber/thumbnails/shirli.jpg",
    "Sirin": "vtuber/thumbnails/sirin.jpg",
    "Six": "vtuber/thumbnails/six.jpg",
    "Skirk": "vtuber/thumbnails/skirk.jpg",
    "Smol Herta": "vtuber/thumbnails/smol_herta.jpg",
    "Soft Kitty": "vtuber/thumbnails/soft_kitty.jpg",
    "Test Model": "vtuber/thumbnails/test.jpg",
    "Toon Anata": "vtuber/thumbnails/toon_anata.jpg",
    "Topaz": "vtuber/thumbnails/topaz.jpg",
    "Vocaloid Miku": "vtuber/thumbnails/vocaloid_miku.jpg",
    "WINE": "vtuber/thumbnails/wine.jpg",
    "Yae Miko": "vtuber/thumbnails/yae_miko.jpg",
    "Zeke": "vtuber/thumbnails/zeke.jpg",
    "Fu Hua Swimsuit": "vtuber/thumbnails/fu_hua_swimsuit.jpg",
    "Fu Hua Herrscher of Sentience": "vtuber/thumbnails/fu_hua_hos.jpg",
    "Kiana Herrscher of the Void": "vtuber/thumbnails/kiana_hov.jpg",
};
